2015/03/29 00:54:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\OpenServer\domains\mydomain\protected\controllers\AnswersController.php:157
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\controllers\AnswersController.php(55): AnswersController->loadModel('1')
#1 [internal function]: AnswersController->actionView('1')
#2 C:\OpenServer\domains\mydomain\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(AnswersController), Array)
#3 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(AnswersController), Object(ReflectionMethod), Array)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\OpenServer\domains\mydomain\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\OpenServer\domains\mydomain\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\OpenServer\domains\mydomain\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\OpenServer\domains\mydomain\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\OpenServer\domains\mydomain\framework\web\CController.php(291): CFilterChain->run()
#11 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('answers/view')
#14 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/answers/1
---
2015/03/29 15:05:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "index.php".' in C:\OpenServer\domains\mydomain\framework\web\CController.php:483
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('answers/index.p...')
#3 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/answers/index.php
---
2015/03/29 15:06:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "answers1".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('answers1')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/answers1
---
2015/03/29 15:11:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "css/style.css".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('css/style.css')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/css/style.css
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:11:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:12:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "css/style.css".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('css/style.css')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/css/style.css
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:12:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:15:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:16:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:17:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:17:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:22:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:25:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:26:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 15:36:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 16:11:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 16:12:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 16:16:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 16:16:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 16:28:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "router.js".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('router.js')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/router.js
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/29 23:21:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "rules".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('rules')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/rules
HTTP_REFERER=http://mydomain/index.php
---
2015/03/29 23:22:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "rules".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('rules')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/rules
HTTP_REFERER=http://mydomain/index.php
---
2015/03/29 23:22:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "rules".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('rules')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/rules
---
2015/03/29 23:24:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "logout".' in C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('logout')
#1 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/logout
---
2015/03/30 00:03:04 [error] [php] Invalid argument supplied for foreach() (C:\OpenServer\domains\mydomain\protected\views\site\index.php:44)
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): SiteController->runAction()
#6 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\OpenServer\domains\mydomain\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php
in C:\OpenServer\domains\mydomain\protected\views\site\index.php (44)
in C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php (32)
in C:\OpenServer\domains\mydomain\index.php (13)
2015/03/30 00:34:29 [error] [php] Invalid argument supplied for foreach() (C:\OpenServer\domains\mydomain\protected\views\site\index.php:44)
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): SiteController->runAction()
#6 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\OpenServer\domains\mydomain\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php
in C:\OpenServer\domains\mydomain\protected\views\site\index.php (44)
in C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php (32)
in C:\OpenServer\domains\mydomain\index.php (13)
2015/03/30 00:34:33 [error] [php] Invalid argument supplied for foreach() (C:\OpenServer\domains\mydomain\protected\views\site\index.php:44)
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): SiteController->runAction()
#6 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\OpenServer\domains\mydomain\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php
in C:\OpenServer\domains\mydomain\protected\views\site\index.php (44)
in C:\OpenServer\domains\mydomain\protected\controllers\SiteController.php (32)
in C:\OpenServer\domains\mydomain\index.php (13)
2015/03/30 00:44:16 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\index.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(17): CController->render('index', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionIndex()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/index')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/index
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/30 00:56:39 [error] [exception.CException] exception 'CException' with message 'Контроллер TestsController не может найти представление "protected/views/tests/tests.php".' in C:\OpenServer\domains\mydomain\framework\web\CController.php:878
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('protected/views...', NULL, true)
#1 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(51): CController->render('protected/views...')
#2 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#7 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#8 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php/tests/tests
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/30 00:57:03 [error] [exception.CException] exception 'CException' with message 'Контроллер TestsController не может найти представление "protected/views/tests/tests.php".' in C:\OpenServer\domains\mydomain\framework\web\CController.php:878
Stack trace:
#0 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('protected/views...', NULL, true)
#1 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(51): CController->render('protected/views...')
#2 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#7 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#8 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 00:57:33 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', NULL, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', NULL, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', NULL, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(51): CController->render('tests')
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 01:00:37 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', NULL, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', NULL, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', NULL, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests')
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/30 01:01:12 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/30 01:01:16 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
HTTP_REFERER=http://mydomain/index.php/
---
2015/03/30 01:01:23 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(16): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 23:28:43 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(6): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 23:31:59 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(6): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 23:32:25 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:173
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(13): CComponent->__set('', '{"response":0, ...')
#1 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#2 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#6 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#7 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/03/30 23:32:59 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "TestsController.".' in C:\OpenServer\domains\mydomain\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\mydomain\protected\views\tests\tests.php(6): CComponent->__get('')
#1 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\mydomain\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\mydomain\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\mydomain\framework\web\CController.php(782): CController->renderPartial('tests', Array, true)
#5 C:\OpenServer\domains\mydomain\protected\controllers\TestsController.php(50): CController->render('tests', Array)
#6 C:\OpenServer\domains\mydomain\framework\web\actions\CInlineAction.php(49): TestsController->actionTests()
#7 C:\OpenServer\domains\mydomain\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\mydomain\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\mydomain\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(282): CController->run('tests')
#11 C:\OpenServer\domains\mydomain\framework\web\CWebApplication.php(141): CWebApplication->runController('tests/tests')
#12 C:\OpenServer\domains\mydomain\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\OpenServer\domains\mydomain\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/tests/tests
---
2015/04/15 00:23:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('name', '2')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:23:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('name', '2')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:25:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('name', '2')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:27:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('name', '2')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:27:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('name', '1')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:28:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('fff', '1')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:30:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('ddd', '2')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:31:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('ddd', '1')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 00:32:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'proforientation'@'localhost' (using password: YES)' in D:\opt\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 D:\opt\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 D:\opt\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 D:\opt\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 D:\opt\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 D:\opt\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 D:\opt\yii\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 D:\opt\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(UserSession))
#7 D:\opt\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(75): CActiveRecord->__construct()
#9 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('ggg', '1')
#10 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:02:40 [error] [exception.CHttpException.405] exception 'CHttpException' with message 'Method Not Allowed' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:53
Stack trace:
#0 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#1 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#5 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#6 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#7 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:02:45 [error] [exception.CHttpException.405] exception 'CHttpException' with message 'Method Not Allowed' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:53
Stack trace:
#0 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#1 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#5 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#6 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#7 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:16:03 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest(NULL, NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:16:06 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest(NULL, NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:16:22 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:20:46 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:36:00 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:36:04 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', '2')
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:38:57 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:39:01 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:39:06 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:40:45 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:41:40 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:45:03 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:46:28 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:46:41 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:49:13 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:51:17 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:51:21 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:51:59 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:52:03 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:73
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('r', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:55:12 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:56:53 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 01:58:18 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:00:13 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:73
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:03:16 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:06:14 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:06:20 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:06:24 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:57:15 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 10:57:21 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:73
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('\xD1\x8B', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
2015/04/15 15:06:08 [error] [exception.CHttpException.402] exception 'CHttpException' with message 'Should be Authorized' in D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php:68
Stack trace:
#0 D:\OpenServer\domains\ProofOrientation\server\protected\controllers\SiteController.php(46): SiteController->startTest('', NULL)
#1 D:\opt\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\opt\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\opt\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\opt\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\opt\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 D:\opt\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#7 D:\opt\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\OpenServer\domains\ProofOrientation\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/index.php
HTTP_REFERER=http://prooforientation/
---
